# Identification of enhancers case study 

This section will present a comparative analysis to demonstrate the application and performance of proPythia for addressing sequence-based prediction problems.

We'll try to replicate one of the [BioSeq-Analysis](https://academic.oup.com/nar/article/47/20/e127/5559689?login=true) case studies for identifying [enhancers](https://academic.oup.com/bioinformatics/article/32/3/362/1744331?login=true#btv604-M1).

In [162]:
%load_ext autoreload

import sys
import pandas as pd

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer, matthews_corrcoef
from sklearn.preprocessing import StandardScaler

sys.path.append('../../../../src/')
from propythia.shallow_ml import ShallowML

from descriptors import DNADescriptor

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [163]:
import csv

def write_dict_to_csv(d: dict, filename: str):
    """
    Writes a dictionary to a csv file.
    """
    with open(filename, 'w') as csv_file:
        writer = csv.writer(csv_file)
        headers = ["id", "sequence"]
        writer.writerow(headers)
        for key, val in d.items():
            writer.writerow([key, val])

In [164]:
from sequence import ReadDNA

dna = ReadDNA()
dna.read_fasta_in_folder('enhancer_dataset')
for i in dna.d:
    write_dict_to_csv(dna.d[i], f'enhancer_dataset/{i}.csv')

This dataset has **742** weak enhancers, **742** strong enhancers, and **1484** non-enhancers.

In [165]:
strong_file =  r'enhancer_dataset/strong.csv'
weak_file =  r'enhancer_dataset/weak.csv'
non_file =  r'enhancer_dataset/non-enhancers.csv'

strong = pd.read_csv(strong_file)
weak = pd.read_csv(weak_file)
non = pd.read_csv(non_file)

print('strong', strong.shape)
print('weak', weak.shape)
print('non', non.shape)

strong (742, 2)
weak (742, 2)
non (1484, 2)


To calculate features, and to be more easy, we create a function to calculate features, calculating all available DNA features.

In [166]:
# List of descriptors to be calculed. If empty, all descriptors will be calculated.
specifics = ["binary"]

In [167]:
def calculate_feature(data):
    list_feature = []
    count = 0
    for seq in data['sequence']:
        res = {'sequence': seq}
        dna = DNADescriptor(seq)
        feature = dna.get_descriptors(specifics=specifics)
        res.update(feature)
        list_feature.append(res)
        
        # print progress every 100 sequences
        if count % 100 == 0:
            print(count, '/', len(data))

        count += 1
    print("Done!")
    df = pd.DataFrame(list_feature)
    return df

strong_feature = calculate_feature(strong)
weak_feature = calculate_feature(weak)
non_feature = calculate_feature(non)

0 / 742
100 / 742
200 / 742
300 / 742
400 / 742
500 / 742
600 / 742
700 / 742
Done!
0 / 742
100 / 742
200 / 742
300 / 742
400 / 742
500 / 742
600 / 742
700 / 742
Done!
0 / 1484
100 / 1484
200 / 1484
300 / 1484
400 / 1484
500 / 1484
600 / 1484
700 / 1484
800 / 1484
900 / 1484
1000 / 1484
1100 / 1484
1200 / 1484
1300 / 1484
1400 / 1484
Done!


- In the dataframe, each row is a sequence and each column is a feature.
- There are 19 different features for each sequence.

In [168]:
# put labels for each dataset   
strong_feature['label'] = 2
weak_feature['label'] = 1
non_feature['label'] = 0

print(strong_feature.shape)
print(weak_feature.shape)
print(non_feature.shape)

(742, 3)
(742, 3)
(1484, 3)


In [169]:
dataset = pd.concat([strong_feature, weak_feature, non_feature])

fps_y = dataset['label']
fps_x = dataset.loc[:, dataset.columns != 'label']
fps_x = fps_x.loc[:, fps_x.columns != 'sequence']

print(fps_x.shape)

(2968, 1)


In [170]:
no_need_normalization = ["length", "at_content", "gc_content"]

need_dict_normalization = ["nucleic_acid_composition", "enhanced_nucleic_acid_composition","dinucleotide_composition","trinucleotide_composition","k_spaced_nucleic_acid_pairs","kmer","PseDNC", "PseKNC"]

need_list_normalization = ["nucleotide_chemical_property", "accumulated_nucleotide_frequency", "DAC", "DCC", "DACC", "TAC","TCC","TACC", "binary"]

def normalize_dict(d, field):
    df = pd.json_normalize(d)
    df.columns = [str(field) + "_" + str(i) for i in df.columns]
    
    for f in df.columns:
        if isinstance(df[f][0], dict):
            df = pd.concat([df, normalize_dict(df[f], f)], axis=1)
            df.drop(f, axis=1, inplace=True)
    return df

def normalize_list(l, field):
    df = pd.DataFrame(l.to_list())
    df.columns = [str(field) + "_" + str(i) for i in df.columns]
    
    for f in df.columns:
        if isinstance(df[f][0], list):
            df = pd.concat([df, normalize_list(df[f], f)], axis=1)
            df.drop(f, axis=1, inplace=True)
    return df

new_fps_x = pd.DataFrame()

for col in fps_x.columns:
    if col in need_dict_normalization:
        new_fps_x = pd.concat([new_fps_x, normalize_dict(fps_x[col], col)], axis=1)
    elif col in need_list_normalization:
        new_fps_x = pd.concat([new_fps_x, normalize_list(fps_x[col], col)], axis=1)
    else:
        new_fps_x[col] = fps_x[col].to_numpy()
        
new_fps_x

binary_0_0  binary_0_1  binary_0_2  binary_0_3  binary_1_0  binary_1_1  \
0              0           1           0           0           1           0   
1              0           0           1           0           0           1   
2              0           0           1           0           1           0   
3              0           1           0           0           0           1   
4              1           0           0           0           0           1   
...          ...         ...         ...         ...         ...         ...   
2963           0           0           0           1           0           0   
2964           1           0           0           0           0           1   
2965           0           1           0           0           1           0   
2966           1           0           0           0           1           0   
2967           1           0           0           0           1           0   

      binary_1_2  binary_1_3  binary_2_0  binary_2_1  ...  binary_197_2  \
0              0           0           0           1  ...             0   
1              0           0           0           1  ...             0   
2              0           0           0           0  ...             0   
3              0           0           0           0  ...             0   
4              0           0           1           0  ...             0   
...          ...         ...         ...         ...  ...           ...   
2963           1           0           1           0  ...             0   
2964           0           0           0           0  ...             0   
2965           0           0           0           0  ...             0   
2966           0           0           0           1  ...             0   
2967           0           0           0           0  ...             0   

      binary_197_3  binary_198_0  binary_198_1  binary_198_2  binary_198_3  \
0                0             0             0             0             1   
1                0             0             1             0             0   
2                0             0             1             0             0   
3                0             1             0             0             0   
4                0             0             0             0             1   
...            ...           ...           ...           ...           ...   
2963             1             1             0             0             0   
2964             0             1             0             0             0   
2965             0             1             0             0             0   
2966             0             0             1             0             0   
2967             1             0             0             0             1   

      binary_199_0  binary_199_1  binary_199_2  binary_199_3  
0                0             0             0             1  
1                0             1             0             0  
2                1             0             0             0  
3                0             0             1             0  
4                1             0             0             0  
...            ...           ...           ...           ...  
2963             1             0             0             0  
2964             0             0             0             1  
2965             0             0             1             0  
2966             0             0             0             1  
2967             0             1             0             0  

[2968 rows x 800 columns]

In [171]:
X_train, X_test, y_train, y_test = train_test_split(new_fps_x, fps_y, stratify=fps_y)

scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# open a ShallowML object
ml = ShallowML(X_train, X_test, y_train, y_test, report_name=None, columns_names=new_fps_x.columns)

# define param grid as article, here we will search in 100, 200 and 500 estimators
param_grid = [{'clf__n_estimators': [100, 200, 500], 'clf__max_features': ['sqrt']}]

# rain_best_model will perform a GRIDSEARCHCV optimizing MCC with a cv = 10
best_rf_model_enhancers = ml.train_best_model(model_name=None, model='rf', score=make_scorer(matthews_corrcoef), param_grid=param_grid, cv=10)

performing gridSearch...
GridSearchCV took 5.65 seconds for 3 candidate parameter settings.
GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('scl', None),
                                       ('clf',
                                        RandomForestClassifier(random_state=1))]),
             n_jobs=10,
             param_grid=[{'clf__max_features': ['sqrt'],
                          'clf__n_estimators': [100, 200, 500]}],
             scoring=make_scorer(matthews_corrcoef))
Model with rank: 1
 Mean validation score: 0.188 (std: 0.055)
 Parameters: {'clf__max_features': 'sqrt', 'clf__n_estimators': 100}
 

Model with rank: 2
 Mean validation score: 0.178 (std: 0.050)
 Parameters: {'clf__max_features': 'sqrt', 'clf__n_estimators': 200}
 

Model with rank: 3
 Mean validation score: 0.163 (std: 0.039)
 Parameters: {'clf__max_features': 'sqrt', 'clf__n_estimators': 500}
 

make_scorer(matthews_corrcoef)
10
Best score (scorer: make_scorer(matthews_corrcoef)) and parameters f

In [172]:
scores, report, cm, cm2 = ml.score_testset(best_rf_model_enhancers)
print(report)
print(cm)  
scores

              precision    recall  f1-score   support

           0       0.54      0.98      0.69       371
           1       0.33      0.04      0.08       185
           2       0.45      0.11      0.18       186

    accuracy                           0.53       742
   macro avg       0.44      0.38      0.32       742
weighted avg       0.46      0.53      0.41       742

[[362   3   6]
 [157   8  20]
 [152  13  21]]


{'Accuracy': 0.5269541778975741,
 'MCC': 0.1528311915188714,
 'log_loss': 0.9691113933743281,
 'f1 score weighted': 0.4116818432198736,
 'f1 score macro': 0.31721006433412896,
 'f1 score micro': 0.5269541778975741,
 'roc_auc ovr': 0.7086888168597539,
 'roc_auc ovo': 0.6782757154317953,
 'precision': 0.4648585735416358,
 'recall': 0.5269541778975741}

In [173]:
# SVM MODEL

# best_rf_model_enhancers = ml.train_best_model(model_name=None,model='svm', scaler=None,
#                 score=make_scorer(matthews_corrcoef),
#                 cv=10, optType='gridSearch', param_grid=None,
#                 n_jobs=10,
#                 random_state=1, n_iter=15, refit=True)